---
- name: Install python-apt
  yum:
    name: python
    state: latest

- name: Download Open JDK
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: validate if Java is availble
  shell:
    java -version

- name: Create the group
  become: yes
  group:
    name: tomcat
    state: present

- name: Create the user
  become: yes
  user:
    name: tomcat
    state: present

- name: Create a Directory /opt/tomcat8
  become: yes
  file:
    path: /opt/tomcat8
    state: directory
    mode: 0755
    owner: tomcat
    group: tomcat

- name: Download Tomcat using unarchive
  become: yes
  unarchive:
    src: "{{download_url}}"
    dest: /opt/tomcat8
    mode: 0755
    remote_src: yes
    group: tomcat
    owner: tomcat

- name: Change directory
  command: cd /opt/tomcat8
  
- name: Change group
  command: sudo chgrp -R tomcat /opt/tomcat8

- name: Change mode
  command: sudo chmod -R g+r+x /opt/tomcat8

- name: change ownership
  command: sudo chown -R tomcat /opt/tomcat8

- name: Extract package
  copy:
    src: /opt/tomcat8/apache-tomcat-8.5.90/
    dest: /opt/tomcat8
    remote_src: True
    group: tomcat
    owner: tomcat
    mode: 0644

- name: Creating a service file
  copy:
    content: |-
      [Unit]
      Description=Tomcat Service
      Requires=network.target
      After=network.target

      [Service]
      Type=forking
      User=tomcat
      
      Environment="CATALINA_PID=/opt/tomcat8/apache-tomcat-8.5.90/temp/tomcat.pid"
      Environment="CATALINA_BASE=/opt/tomcat8/apache-tomcat-8.5.90"
      Environment="CATALINA_HOME=/opt/tomcat8/apache-tomcat-8.5.90"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
      
      ExecStart=/opt/tomcat8/apache-tomcat-8.5.90/bin/startup.sh
      ExecStop=/opt/tomcat8/apache-tomcat-8.5.90/bin/shutdown.sh
      
      Group=tomcat
      UMask=0007
      RestartSec=10
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/tomcat.service



- name: Reload the SystemD to re-read configurations
  become: yes
  systemd:
    daemon-reload: yes

- name: Enable the tomcat service and start
  become: yes
  systemd:
	name: ansible
    enabled: yes
    state: started

- name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
  tags: test
  uri:
    url: http://43.205.242.132:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10